"""Full, audited six-family direct comparison on the thirteen-year cohort."""
import json

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from inseason_13year_data import ROOT, CACHE, BLOCKS, YEARS, RECIPES, load, partition
from inseason_nested_common import LABELS
from inseason_13year_uncertainty import historical, interval
from review_revision_data import sha256
from run_inseason_13year_direct import root_for as original_root, CODE as ORIGINAL_CODE
from run_inseason_direct_extension import root_for as extra_root, verify as verify_extra
from run_inseason_forest_cpu import root_for as forest_root, verify as verify_forest
from run_inseason_direct_baselines import score
from run_ndvi_signal_permutation import check_files
from run_review_revision_parallel import atomic_json
from summarize_inseason_13year import annual_gain

OUT = ROOT / 'visualize/paper_experiments/inseason_direct_extension_v1'
TEX = ROOT / 'Paper/iclr2027/sections'
ORIGINAL = ('lightgbm', 'gru', 'transformer')
MODELS = ('ridge', 'random_forest', 'lightgbm', 'gru', 'transformer', 'cnn_rnn')
NAMES = dict(ridge='Ridge', random_forest='Random Forest', lightgbm='LightGBM',
    gru='GRU', transformer='Transformer', cnn_rnn='CNN-RNN (adapted)',
    world='Frozen world-model pipeline', history='Strong historical reference')
CN = dict(maize='玉米', rice='水稻', soybean='大豆', wheat='小麦')


def model_root(crop, cutoff, model):
    resolver = original_root if model in ORIGINAL else forest_root if model == 'random_forest' else extra_root
    return resolver(crop,cutoff,model)


def complete_score(labels, prediction):
    if tuple(np.unique(labels['year'])) != YEARS:
        raise ValueError('Incomplete thirteen-year direct comparison')
    if prediction.shape != labels['target'].shape or not np.isfinite(prediction).all():
        raise ValueError('Invalid or nonfinite direct prediction')
    keys = np.rec.fromarrays([labels[k] for k in ('year', 'row', 'col')])
    if len(np.unique(keys)) != len(keys):
        raise ValueError('Duplicated evaluation identity')
    return score(labels['target'], prediction, labels['year'])


def table(name, caption, label, header, columns, rows, placement='t'):
    (TEX / name).write_text('% Generated by scripts/summarize_inseason_six_direct.py\n'
        f'\\begin{{table}}[{placement}]\n\\centering\\small\n'
        f'\\caption{{{caption}}}\n\\label{{{label}}}\n'
        f'\\begin{{tabular}}{{{columns}}}\n\\toprule\n{header} \\\\\n\\midrule\n'
        +'\n'.join(rows)+'\n\\bottomrule\n\\end{tabular}\n\\end{table}\n')


def collect():
    rows, annual, paired, registry, sources, runtimes, intervals = [], [], [], [], {}, [], []
    comparison_path = ROOT / 'visualize/paper_experiments/inseason_13year_v1/comparisons.csv'
    refs = pd.read_csv(comparison_path).set_index('crop')
    sources[str(comparison_path)] = sha256(comparison_path)
    helper = ROOT / 'scripts/inseason_13year_uncertainty.py'
    sources[str(helper)] = sha256(helper)
    old_code = {name: sha256(ROOT / 'scripts' / name) for name in ORIGINAL_CODE}
    for crop, recipe in RECIPES.items():
        raw, _ = load(crop)
        sources[str(CACHE / crop / 'manifest.json')] = sha256(CACHE / crop / 'manifest.json')
        labels = {key: np.concatenate([raw[key][partition(raw, cutoff)['evaluation']]
                  for cutoff in BLOCKS]) for key in LABELS}
        baseline_parts = []
        for cutoff in BLOCKS:
            ix = partition(raw, cutoff)['evaluation']
            part = {key: raw[key][ix] for key in LABELS}
            baseline_parts.append(historical(crop, cutoff, refs.loc[crop, 'baseline'], part, sources))
            for model in MODELS:
                root = model_root(crop, cutoff, model)
                if model in ORIGINAL:
                    marker = json.loads((root / 'complete.json').read_text())
                    check_files(root, marker['files'])
                    if marker['code_sha256'] != old_code:
                        raise ValueError('Changed original direct source')
                elif model == 'random_forest':
                    marker = verify_forest(root)
                else:
                    marker = verify_extra(root)
                config = json.loads((root / 'config.json').read_text())
                if marker['smoke'] or config['crop'] != crop or config['cutoff'] != cutoff or config['seed'] != 42:
                    raise ValueError('Invalid direct model registration')
                sources[str(root / 'complete.json')] = sha256(root / 'complete.json')
                runtimes.append(dict(crop=crop, cutoff=cutoff, model=model,
                    three_suffix_pipeline_seconds=marker['seconds']))
        for percent in (10,30,50):
            outputs = dict(history=np.concatenate(baseline_parts))
            for model in MODELS:
                chunks = []
                for cutoff in BLOCKS:
                    ix = partition(raw, cutoff)['evaluation']
                    root = model_root(crop, cutoff, model)
                    dest = root / f'tail_{percent:02d}'
                    path = dest / 'evaluation_predictions.npz'
                    with np.load(path) as saved:
                        for key in LABELS:
                            np.testing.assert_array_equal(saved[key], raw[key][ix])
                        chunks.append(saved['prediction'].copy())
                    sources[str(path)] = sha256(path)
                    weight = dest / ('model.pt' if model in ('gru','transformer','cnn_rnn') else 'model.joblib')
                    registry.append(dict(crop=crop, cutoff=cutoff, model=model, percent=percent, seed=42,
                        weight=str(weight), weight_sha256=sha256(weight),
                        metrics=str(dest / 'metrics.json'), predictions=str(path),
                        config=str(root / 'config.json'), manifest=str(root / 'complete.json')))
                outputs[model] = np.concatenate(chunks)
            pieces = []
            for cutoff in BLOCKS:
                path = CACHE / crop / f'world_{cutoff}_{recipe}_biid_{percent:03d}.npy'
                sources[str(path)] = sha256(path)
                pieces.append(np.load(path))
            outputs['world'] = np.concatenate(pieces)
            for model, prediction in outputs.items():
                metrics = complete_score(labels, prediction)
                rows.append(dict(crop=crop, model=model, percent=percent,
                    pooled_rmse=metrics['pooled_rmse'], mean_annual_rmse=metrics['mean_annual_rmse']))
                annual.extend(dict(crop=crop, model=model, percent=percent, year=int(year), rmse=error)
                              for year, error in metrics['per_year_rmse'].items())
                if model != 'world':
                    paired.append(dict(crop=crop, reference=model, percent=percent,
                        **annual_gain(labels['target'], outputs['world'], prediction, labels['year'])))
                if percent == 10 and model in MODELS:
                    for degrees in (10,20):
                        intervals.append(dict(crop=crop,reference=model,percent=percent,
                            **interval(labels,outputs['world'],prediction,degrees)))
    if len(registry) != 216:
        raise ValueError('Expected 216 final direct models, including 108 reused')
    return pd.DataFrame(rows), pd.DataFrame(annual), pd.DataFrame(paired), registry, sources, runtimes, refs, pd.DataFrame(intervals)


def figures(frame, references):
    plt.rcParams.update({'font.family':'DejaVu Sans', 'font.size':10, 'pdf.fonttype':42})
    colors = dict(ridge='#767676', random_forest='#d39b22', lightgbm='#ba6338',
        gru='#3267a3', transformer='#985d91', cnn_rnn='#46a1ad', world='#1c7c68')
    fig, axes = plt.subplots(2,2,figsize=(10.5,7.8))
    fig.subplots_adjust(left=.10,right=.98,bottom=.21,top=.95,hspace=.45,wspace=.32)
    for ax, crop in zip(axes.flat, RECIPES):
        for model in (*MODELS, 'world'):
            part = frame[frame.crop.eq(crop) & frame.model.eq(model)].sort_values('percent')
            ax.plot(part.percent, part.mean_annual_rmse, 'o-', label=NAMES[model],
                    color=colors[model], markersize=4, linewidth=1.5 if model=='world' else 1.1)
        history = frame[frame.crop.eq(crop) & frame.model.eq('history')].mean_annual_rmse.iloc[0]
        ax.axhline(history, color='.25', linestyle='--', linewidth=.9, label=NAMES['history'])
        ax.set_title(crop.title()+' | '+RECIPES[crop].upper().replace('_',' + ')+
            '\nReference: '+references.loc[crop,'baseline_label'], fontsize=9)
        ax.set_xticks([10,30,50])
        ax.set_xlabel('Nominal unobserved suffix (%)')
        ax.set_ylabel('Mean annual yield RMSE (t/ha)')
        ax.grid(axis='y',alpha=.2)
        ax.spines[['top','right']].set_visible(False)
    handles, labels = axes.flat[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='lower center', ncol=3, fontsize=9, frameon=False)
    for ext in ('png','pdf'):
        fig.savefig(OUT / f'six_direct_comparison.{ext}', dpi=220, bbox_inches='tight')
    plt.close(fig)


def export(frame, paired, intervals):
    for detailed in (False,True):
        rows = []
        for percent in ((10,30,50) if detailed else (10,)):
            part = frame[frame.percent.eq(percent)].pivot(index='model',columns='crop',values='mean_annual_rmse')
            for model in ('history', *MODELS, 'world'):
                name = r'\method{} (frozen readout)' if model=='world' else NAMES[model]
                cells = ([f'{percent}\\%'] if detailed else [])+[name]+[f'{part.loc[model,c]:.4f}' for c in RECIPES]
                rows.append(' & '.join(cells)+r' \\')
            if detailed and percent != 50:
                rows.append(r'\midrule')
        table('inseason_six_direct_leads.tex' if detailed else 'inseason_six_direct_table.tex',
            'Six direct seasonal baseline families on the same thirteen-year cohort'+
            ('. ' if detailed else ' at a 10\\% unobserved suffix. ')+
            'Entries are mean annual yield RMSE (t/ha). Direct methods share inputs and the causal-trend anchor; '
            'the world-model pipeline retains its original crop-specific anchors. CNN--RNN is an input-matched adaptation. '
            'Historical references are named in Table~\\ref{tab:inseason_13year_gains}.',
            'tab:inseason_13year_direct_leads' if detailed else 'tab:inseason_13year_direct',
            ('Suffix & ' if detailed else '')+'Method & Maize & Rice & Soybean & Wheat',
            'llrrrr' if detailed else 'lrrrr', rows, 'htbp' if detailed else 't')
    part = frame[frame.percent.eq(10)].pivot(index='model',columns='crop',values='mean_annual_rmse')
    best = part.loc[list(MODELS)].min()
    winners = part.loc[list(MODELS)].idxmin()
    method_names = (NAMES[winners.iloc[0]]+' for all four crops' if winners.nunique()==1 else
        ', '.join(NAMES[winners[c]]+' for '+c for c in RECIPES))
    count = sum(part.loc['world',c] < best[c] for c in RECIPES)
    text = ('At the 10\\% suffix, the lowest direct-model error is attained by '+method_names+'. '
        'The direct minima are '+', '.join(f'{best[c]:.4f}' for c in RECIPES)+' t/ha, respectively. '
        'The frozen world-model pipeline has lower mean annual RMSE for '+
        ('all four crops' if count==4 else f'{count} of the four crops')+'. '
        'All six families and three suffixes are retained; the reported minimum is a comparison statistic, '
        'not a component selected to construct the world model.\n')
    (TEX / 'inseason_six_direct_findings.tex').write_text('% Generated by scripts/summarize_inseason_six_direct.py\n'+text)
    rows = []
    for crop in RECIPES:
        for model in MODELS:
            point = paired[paired.crop.eq(crop) & paired.reference.eq(model) & paired.percent.eq(10)].iloc[0]
            uncertainty = intervals[intervals.crop.eq(crop) & intervals.reference.eq(model)].set_index('degrees')
            cells = [crop.title(),NAMES[model],f'{point.annual_mean_rmse_gain:+.2f}']
            for degrees in (10,20):
                ci = uncertainty.loc[degrees]
                cells.append(f'[{ci.annual_mean_rmse_gain_low:+.2f}, {ci.annual_mean_rmse_gain_high:+.2f}]')
            rows.append(' & '.join(cells)+r' \\')
    table('inseason_six_direct_uncertainty.tex',
        'World-model reductions in mean annual yield RMSE relative to each direct method at a 10\\% suffix. '
        'Paired 95\\% intervals use 1,000 spatial-block draws, retaining all thirteen years. '
        'These intervals condition on the fitted methods and do not include seed or model-selection uncertainty.',
        'tab:inseason_direct_uncertainty','Crop & Direct reference & Gain (\\%) & 10-degree blocks & 20-degree blocks',
        'llrrr',rows,'htbp')
    lines = ['# 六类直接季中基线：十三年结果', '',
        '本批补齐Ridge、Random Forest和CNN–RNN适配版；与既有LightGBM、GRU、Transformer合并，共216个最终配置，新增108个。固定seed42、同样13年和同样样本。', '',
        '## 主截点比较', '', '以下为10%名义未观测后缀的年度RMSE等权平均（吨/公顷，越小越好）。', '',
        '| 方法 | 玉米 | 水稻 | 大豆 | 小麦 |', '|---|---:|---:|---:|---:|']
    for model in ('history', *MODELS, 'world'):
        lines.append('| '+NAMES[model]+' | '+' | '.join(f'{part.loc[model,c]:.4f}' for c in RECIPES)+' |')
    lines += ['', '## 世界模型相对最强直接基线', '']
    for crop in RECIPES:
        matched = paired[paired.crop.eq(crop) & paired.percent.eq(10) & paired.reference.eq(winners[crop])].iloc[0]
        lines.append(f'- {CN[crop]}：最低直接误差来自{NAMES[winners[crop]]}；世界模型年均RMSE降幅'
            f'{matched.annual_mean_rmse_gain:+.2f}%，{int(matched.positive_years)}/13年更好。')
    lines += ['', '该参照在一个作物的整个13年上固定，不逐年换基线。新增方法无论优劣都保留。', '',
        f'![六类直接模型与世界模型]({OUT}/six_direct_comparison.png)', '',
        '怎么看：每个面板是一种作物，横轴越右需要补全的遥感越多；纵轴越低产量误差越小。虚线是该作物完整历史库的具名固定参照。完整模型比较与同头补全消融不同，不能仅凭这张图把全部收益归因于BIID。', '',
        '## 范围与文件', '',
        'Ridge/Random Forest接收585或693维展平输入；CNN–RNN用CNN编码季内槽，用LSTM编码五年历史值和有效性，再与背景融合。原论文的土壤、管理与历年气象没有被偷偷加入；此项明确为适配版。', '',
        '全部使用实际气象作为给定条件，不是同时截断气象的业务预报实验。单种子不代表已完成随机性确认。', '',
        f'- 全部结果：`{OUT}/scores.csv`。', f'- 逐年结果：`{OUT}/annual.csv`。',
        f'- 世界模型相对每项对照的配对收益：`{OUT}/paired_gains.csv`。',
        f'- 主截点全部六类对手的空间配对区间：`{OUT}/uncertainty.csv`。区间跨过0时，不能仅凭平均正收益宣称空间重采样下稳定优胜。',
        f'- 216个权重索引与哈希：`{OUT}/checkpoint_registry.csv`。',
        f'- 来源核验：`{OUT}/audit.json`。', '',
        '本批完成主比较中缺失的三类方法；状态对照另有独立批次，物候表示与独立标签验证不由这张表替代。']
    (OUT / '结果说明.md').write_text('\n'.join(lines)+'\n')


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    frame, annual, paired, registry, sources, runtimes, references, intervals = collect()
    frame.to_csv(OUT / 'scores.csv', index=False)
    annual.to_csv(OUT / 'annual.csv', index=False)
    paired.to_csv(OUT / 'paired_gains.csv', index=False)
    intervals.to_csv(OUT / 'uncertainty.csv', index=False)
    pd.DataFrame(registry).to_csv(OUT / 'checkpoint_registry.csv', index=False)
    pd.DataFrame(runtimes).to_csv(OUT / 'runtimes.csv', index=False)
    figures(frame, references)
    export(frame, paired, intervals)
    atomic_json(OUT / 'audit.json', dict(sources=sources, final_models=216, new_models=108,
        all_six_methods_and_thirteen_years=True, input_identity_replayed=True,
        generator_sha256=sha256(ROOT / 'scripts/summarize_inseason_six_direct.py'),
        primary_metric='Mean of thirteen annual spatial RMSEs', seed=42))
    print(frame[frame.percent.eq(10)].to_string(index=False), flush=True)


if __name__ == '__main__':
    main()
