"""Full thirteen-year historical comparison with annual and cutoff exhibits."""
import json

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
import numpy as np
import pandas as pd

from inseason_13year_data import ROOT, CACHE, OUT as RUNS, BLOCKS, YEARS, RECIPES, load, partition
from run_inseason_13year_history import root_for, ALL_METHODS, MODELS, CODE
from run_inseason_direct_baselines import score
from run_ndvi_signal_permutation import check_files
from run_review_revision_parallel import atomic_json
from review_revision_data import sha256
from summarize_full_yield_only_suite import METHODS, LABELS
from inseason_13year_extended_history import PREFIX, DISPLAY, extended_predictions, display

OUT = ROOT / 'visualize/paper_experiments/inseason_13year_v1'
TEX = ROOT / 'Paper/iclr2027/sections'


def annual_gain(truth, candidate, reference, years):
    a = score(truth, candidate, years)
    b = score(truth, reference, years)
    gains = np.array([100*(1-v/b['per_year_rmse'][y]) for y, v in a['per_year_rmse'].items()])
    return dict(mean_annual_gain=float(gains.mean()), positive_years=int((gains > 0).sum()),
        annual_mean_rmse_gain=100*(1-a['mean_annual_rmse']/b['mean_annual_rmse']))


def write_table(file, caption, label, header, columns, rows):
    (TEX / file).write_text('% Generated by scripts/summarize_inseason_13year.py\n'
        '\\begin{table}[t]\n\\centering\n\\small\n'
        f'\\caption{{{caption}}}\n\\label{{{label}}}\n'
        f'\\begin{{tabular}}{{{columns}}}\n\\toprule\n{header} \\\\\n\\midrule\n'
        + '\n'.join(rows) + '\n\\bottomrule\n\\end{tabular}\n\\end{table}\n')


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    hashes = {n: sha256(ROOT / 'scripts' / n) for n in CODE}
    sources, rows, annual, comparisons, cutoffs, cohorts, signals, checkpoints = {}, [], [], [], [], [], [], []
    for crop, recipe in RECIPES.items():
        raw, _ = load(crop)
        sources[str(CACHE / crop / 'manifest.json')] = sha256(CACHE / crop / 'manifest.json')
        chunks = {m: [] for m in METHODS}
        identities, frozen, extended = [], {}, {}
        for cutoff in BLOCKS:
            indices = partition(raw, cutoff)['evaluation']
            identities.extend(indices)
            labels={k:raw[k][indices] for k in ('target','source_indices','year','row','col')}
            for name,prediction in extended_predictions(crop,cutoff,labels,sources).items():
                extended.setdefault(name,[]).append(prediction)
            for kind in ('classical', *MODELS):
                root = root_for(crop, cutoff, kind)
                marker = json.loads((root / 'complete.json').read_text())
                check_files(root, marker['files'])
                if marker['code_sha256'] != hashes:
                    raise ValueError('Changed rolling baseline code')
                for name,digest in marker.get('runtime_code_sha256',{}).items():
                    if sha256(ROOT/'scripts'/name)!=digest:
                        raise ValueError('Changed runtime recovery implementation')
                sources[str(root / 'complete.json')] = sha256(root / 'complete.json')
                for method in (ALL_METHODS if kind == 'classical' else (kind,)):
                    path = root / method / 'evaluation_predictions.npz'
                    with np.load(path) as f:
                        for key in ('year', 'row', 'col', 'target', 'source_indices'):
                            np.testing.assert_array_equal(f[key], raw[key][indices])
                        pred = f['prediction']
                    if not np.isfinite(pred).all():
                        raise ValueError('Nonfinite baseline prediction')
                    chunks[method].append(pred)
                    dest=root/method
                    weight=next((dest/n for n in ('model.pt','model.joblib','index.faiss') if (dest/n).exists()),None)
                    checkpoints.append(dict(crop=crop,cutoff=cutoff,method=method,seed=42,
                        weight=str(weight) if weight else 'Statistical rule; no learned weights',
                        metadata=str(dest/'metrics.json'),predictions=str(path),
                        complete_manifest=str(root/'complete.json')))
            for percent in range(0, 101, 10):
                for mode in ('biid', 'climatology'):
                    path = CACHE / crop / f'world_{cutoff}_{recipe}_{mode}_{percent:03d}.npy'
                    frozen.setdefault((mode, percent), []).append(np.load(path))
        indices = np.array(identities)
        year, truth = raw['year'][indices], raw['target'][indices]
        if tuple(np.unique(year)) != YEARS:
            raise ValueError('Incomplete main evaluation years')
        pred = {m: np.concatenate(v) for m, v in chunks.items() if v}
        pred['hgb_mlp_ensemble'] = .5*(pred['hist_gradient_boosting']+pred['mlp'])
        pred['world_model'] = np.concatenate(frozen['biid', 10])
        if set(pred) != set(METHODS):
            raise ValueError('The complete 27-model library must be retained')
        pred.update({name:np.concatenate(parts) for name,parts in extended.items()})
        errors = {}
        for method, values in pred.items():
            metric = score(truth, values, year)
            errors[method] = metric['mean_annual_rmse']
            rows.append(dict(crop=crop, method=method, **metric))
            for y, error in metric['per_year_rmse'].items():
                annual.append(dict(crop=crop, method=method, year=int(y), rmse=error))
        strongest = min((m for m in pred if m!='world_model'), key=errors.get)
        comparisons.append(dict(crop=crop, recipe=recipe, baseline=strongest,
            baseline_label=display(strongest) if strongest.startswith(PREFIX) else LABELS[strongest].replace('HGB history expert', 'Histogram gradient boosting'),
            baseline_rmse=errors[strongest], world_rmse=errors['world_model'],
            **annual_gain(truth, pred['world_model'], pred[strongest], year)))
        for (mode, percent), parts in frozen.items():
            values = np.concatenate(parts)
            metric = score(truth, values, year)
            cutoffs.append(dict(crop=crop, mode=mode, percent=percent,
                mean_annual_rmse=metric['mean_annual_rmse'], baseline=strongest,
                **annual_gain(truth, values, pred[strongest], year)))
        for alternative in ('ndvi', 'gpp', 'ndvi_gpp'):
            for percent in range(0, 101, 10):
                values = np.concatenate([np.load(CACHE / crop /
                    f'world_{end}_{alternative}_biid_{percent:03d}.npy') for end in BLOCKS])
                signals.append(dict(crop=crop, recipe=alternative, percent=percent,
                    baseline=strongest, **annual_gain(truth, values, pred[strongest], year)))
        active = raw['relative_valid'][indices] > 0
        slots = active.sum(1)
        grid = raw['row'][indices].astype(int)*720+raw['col'][indices]
        cohorts.append(dict(crop=crop, grid_years=len(indices), cells=len(np.unique(grid)),
            median_slots=float(np.median(slots)), median_hidden_percent=float(np.median(100*np.ceil(.1*slots)/slots))))
    scores, yearly, compared, curves = map(pd.DataFrame, (rows, annual, comparisons, cutoffs))
    for name, frame in (('baseline27', scores), ('annual', yearly), ('comparisons', compared),
                        ('cutoffs', curves), ('cohort', pd.DataFrame(cohorts)), ('signals', pd.DataFrame(signals)),
                        ('checkpoint_registry',pd.DataFrame(checkpoints))):
        frame.drop(columns='per_year_rmse', errors='ignore').to_csv(OUT / f'{name}.csv', index=False)
    scores[scores.method.isin(METHODS)].drop(columns='per_year_rmse').to_csv(OUT/'baseline27.csv',index=False)
    scores[scores.method.str.startswith(PREFIX)].drop(columns='per_year_rmse').to_csv(OUT/'extended.csv',index=False)
    scores.drop(columns='per_year_rmse').to_csv(OUT/'all_historical.csv',index=False)
    matrix = scores.pivot(index='method', columns='crop', values='mean_annual_rmse')
    table_rows = []
    main_methods=[*METHODS[:-1],*[PREFIX+n for n in DISPLAY], 'world_model']
    for method in main_methods:
        if method == 'world_model':
            table_rows.append(r'\midrule')
        if method==PREFIX+next(iter(DISPLAY)):
            table_rows.append(r'\midrule')
        label = r'\method{} (10\% suffix)' if method == 'world_model' else (
            display(method) if method.startswith(PREFIX) else LABELS[method].replace('HGB history expert', 'Histogram gradient boosting'))
        cells = []
        for crop in RECIPES:
            value = matrix.loc[method, crop]
            text = f'{value:.4f}'
            if value == matrix[crop].min():
                text = r'\textbf{' + text + '}'
            cells.append(text)
        table_rows.append(label+' & '+' & '.join(cells)+r' \\')
    write_table('inseason_13year_baselines_table.tex',
        'Main thirteen-year yield comparison. Entries are mean annual RMSE (t/ha), '
        'with each of the thirteen evaluation years weighted equally; lower is better. '
        'All 27 historical algorithms, four stronger archived variants, and the fixed seasonal recipe are shown. '
        'The complete fifteen-variant extension is in Table~\\ref{tab:inseason_13year_extended}. '
        'Bold denotes the lowest error within each crop. Seed 42; protocol in '
        'Table~\\ref{tab:inseason_13year_protocol}.', 'tab:inseason_13year_baselines',
        'Method & Maize & Rice & Soybean & Wheat', 'lrrrr', table_rows)
    pooled=scores.pivot(index='method',columns='crop',values='pooled_rmse')
    pooled_rows=[]
    for method in METHODS:
        label=r'\method{} (10\% suffix)' if method=='world_model' else LABELS[method].replace('HGB history expert','Histogram gradient boosting')
        pooled_rows.append(label+' & '+' & '.join(f'{pooled.loc[method,c]:.4f}' for c in RECIPES)+r' \\')
    write_table('inseason_13year_pooled_table.tex',
        'Pooled grid--year RMSE (t/ha) for the same thirteen-year prediction vectors. '
        'This is a secondary aggregation; the primary comparison weights annual RMSEs equally.',
        'tab:inseason_13year_pooled','Method & Maize & Rice & Soybean & Wheat','lrrrr',pooled_rows)
    extended_rows=[]
    for method in sorted(m for m in matrix.index if m.startswith(PREFIX)):
        label=display(method).replace('lambda=',r'$\lambda=$')
        extended_rows.append(label+' & '+' & '.join(f'{matrix.loc[method,c]:.4f}' for c in RECIPES)+r' \\')
    write_table('inseason_13year_extended_table.tex',
        'All fifteen previously retained historical residual configurations, replayed on the '
        'same thirteen-year population. Entries are mean annual RMSE (t/ha). These retain '
        'their original training and development-selection provenance; none is discarded '
        'because it outperforms a newly fitted baseline.',
        'tab:inseason_13year_extended','Historical configuration & Maize & Rice & Soybean & Wheat','lrrrr',extended_rows)
    ordered=compared.set_index('crop').loc[list(RECIPES)]
    wins=int((ordered.world_rmse<ordered.baseline_rmse).sum())
    findings=('Across the thirteen years, \\method{} attains mean annual RMSEs of '
        +', '.join(f'{v:.4f}' for v in ordered.world_rmse)+' for maize, rice, soybean, and wheat. '
        'The corresponding lowest errors across the 27 algorithms and fifteen archived historical variants are '
        +', '.join(f'{v:.4f}' for v in ordered.baseline_rmse)+'. '
        'The seasonal pipeline has lower mean annual RMSE than these references for '
        +('all four crops. ' if wins==4 else f'{wins} of the four crops. ')
        +'Mean paired annual reductions are '+', '.join(f'{v:+.2f}\\%' for v in ordered.mean_annual_gain)
        +', with positive years of '+', '.join(f'{v}/13' for v in ordered.positive_years)+', respectively.\n')
    (TEX/'inseason_13year_main_findings.tex').write_text(findings)
    table_rows = [r.crop.title()+' & '+(r'\makecell[l]{'+r.baseline_label.replace(' (',r'\\(')+'}')+' & '+f'{r.baseline_rmse:.4f} & {r.world_rmse:.4f} & '
        +f'{r.mean_annual_gain:+.2f} & {r.positive_years}/13'+r' \\' for r in compared.itertuples()]
    write_table('inseason_13year_gain_table.tex',
        'The strongest complete-library historical reference for each crop, fixed '
        'across all years and cutoffs. RMSE is a mean over years (t/ha); gain is '
        'the mean of paired annual RMSE reductions (\\%). The comparator is a '
        'descriptive minimum over the complete library, not a per-year model switch.',
        'tab:inseason_13year_gains', 'Crop & Historical reference & Reference & \\method{} & Gain (\\%) & Positive years',
        'llrrrr', table_rows)
    table_rows = [r['crop'].title()+f' & {r["grid_years"]:,} & {r["cells"]:,} & '
        +f'{r["median_slots"]:g} & {r["median_hidden_percent"]:.1f}'+r' \\' for r in cohorts]
    write_table('inseason_13year_cohort_table.tex',
        'The main thirteen-year cohort. Active-slot count and actual hidden fraction '
        'are medians at a nominal 10\\% suffix. All methods share these grid--year identities.',
        'tab:inseason_cohort', 'Crop & Grid--years & Cells & Active slots & Hidden (\\%)', 'lrrrr', table_rows)
    table_rows = []
    for percent in range(0, 101, 10):
        block = curves[curves.percent.eq(percent) & curves['mode'].eq('biid')].set_index('crop')
        table_rows.append(f'{percent}\\% & '+' & '.join(
            f'{block.loc[c, "mean_annual_gain"]:+.2f} ({int(block.loc[c, "positive_years"])}/13)'
            for c in RECIPES)+r' \\')
    write_table('inseason_13year_lead_table.tex',
        'Fixed crop--signal recipes across observation cutoffs in the main thirteen-year '
        'evaluation. Each entry gives mean annual RMSE reduction (\\%) and positive years '
        'against the fixed complete-library reference in Table~\\ref{tab:inseason_13year_gains}.',
        'tab:inseason_13year_leads', 'Suffix & Maize (GPP) & Rice (NDVI) & Soybean (NDVI) & Wheat (both)',
        'lrrrr', table_rows)

    plt.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 10, 'pdf.fonttype': 42})
    fig, axes = plt.subplots(2, 2, figsize=(10.1, 7.1))
    fig.subplots_adjust(left=.10, right=.98, bottom=.16, top=.91, hspace=.47, wspace=.29)
    for ax, crop in zip(axes.flat, RECIPES):
        for mode, label, color in (('biid', 'BIID completion', '#1c7a67'), ('climatology', 'Climatology completion', '#bb653b')):
            part = curves[curves.crop.eq(crop) & curves['mode'].eq(mode) & curves.percent.gt(0)].sort_values('percent')
            ax.plot(part.percent, part.mean_annual_gain, marker='o', color=color, markersize=3, label=label)
        obs = curves[curves.crop.eq(crop) & curves['mode'].eq('biid') & curves.percent.eq(0)].iloc[0]
        ax.scatter([0], [obs.mean_annual_gain], marker='D', color='#555555', s=24, label='Fully observed reference')
        ax.axhline(0, color='#555555', linestyle='--', linewidth=1)
        base = compared[compared.crop.eq(crop)].iloc[0]
        ax.set_title(f'{crop.title()} | {RECIPES[crop].upper().replace("_", " + ")}\nReference: {base.baseline_label}', fontsize=10)
        ax.set_xlabel('Nominal unobserved suffix (%)')
        ax.set_ylabel('Mean annual RMSE reduction (%)')
        ax.grid(axis='y', alpha=.2)
        ax.spines[['top', 'right']].set_visible(False)
    h, l = axes.flat[0].get_legend_handles_labels()
    fig.legend(h, l, loc='lower center', ncol=3, frameon=False, bbox_to_anchor=(.53,.015), fontsize=9)
    for ext in ('pdf', 'png'):
        fig.savefig(OUT / f'cutoff_comparison.{ext}', dpi=220, bbox_inches='tight')
    plt.close(fig)

    signal_frame = pd.DataFrame(signals)
    fig, axes = plt.subplots(2, 2, figsize=(10.1, 7.1))
    fig.subplots_adjust(left=.10, right=.98, bottom=.16, top=.91, hspace=.47, wspace=.29)
    for ax, crop in zip(axes.flat, RECIPES):
        for alternative, label, color in (('ndvi', 'NDVI', '#3267a3'), ('gpp', 'GPP', '#b56b35'),
                                          ('ndvi_gpp', 'NDVI + GPP', '#1e7c69')):
            part = signal_frame[signal_frame.crop.eq(crop) & signal_frame.recipe.eq(alternative)].sort_values('percent')
            ax.plot(part.percent, part.mean_annual_gain, 'o-', color=color, label=label, markersize=3)
        ax.axhline(0, color='#555555', linestyle='--', linewidth=1)
        ax.set_title(crop.title()+' | Thirteen-year evaluation', fontsize=10)
        ax.set_xlabel('Nominal unobserved suffix (%)')
        ax.set_ylabel('Mean annual RMSE reduction (%)')
        ax.grid(axis='y', alpha=.2)
        ax.spines[['top', 'right']].set_visible(False)
    h, l = axes.flat[0].get_legend_handles_labels()
    fig.legend(h, l, loc='lower center', ncol=3, frameon=False, bbox_to_anchor=(.53,.015), fontsize=9)
    for ext in ('pdf', 'png'):
        fig.savefig(OUT / f'signal_matching.{ext}', dpi=220, bbox_inches='tight')
    plt.close(fig)

    values = []
    for crop in RECIPES:
        reference = compared[compared.crop.eq(crop)].iloc[0].baseline
        block = yearly[yearly.crop.eq(crop)].pivot(index='method', columns='year', values='rmse')
        values.append([100*(1-block.loc['world_model', y]/block.loc[reference, y]) for y in YEARS])
    values = np.array(values)
    limit = max(float(np.abs(values).max()), 1.)
    fig, ax = plt.subplots(figsize=(12.2, 3.5), layout='constrained')
    im = ax.imshow(values, cmap='BrBG', norm=TwoSlopeNorm(vmin=-limit, vcenter=0, vmax=limit), aspect='auto')
    ax.set_xticks(range(13), YEARS)
    ax.set_yticks(range(4), [f'{c.title()} ({int((v>0).sum())}/13)' for c, v in zip(RECIPES, values)])
    for i in range(4):
        for j in range(13):
            ax.text(j, i, f'{values[i,j]:+.1f}', ha='center', va='center', fontsize=8,
                    color='white' if abs(values[i,j]) > .6*limit else '#222222')
    ax.set_xlabel('Evaluation year')
    fig.colorbar(im, ax=ax, label='Annual RMSE reduction (%)', fraction=.03)
    for ext in ('pdf', 'png'):
        fig.savefig(OUT / f'annual_gains.{ext}', dpi=220, bbox_inches='tight')
    plt.close(fig)
    atomic_json(OUT / 'audit.json', dict(sources=sources, complete_historical_methods=27,
        complete_extended_historical_configurations=15,
        evaluation_years=YEARS, exact_cohort_replay=True, source_model_hashes_checked=True,
        seed=42, primary_metric='Equal-weight mean of thirteen annual RMSEs',
        world_predictions='Replayed Figure 4 assets; inherited selection history retained',
        new_boosting_selection='Pooled internal validation RMSE',
        new_neural_selection='Mean annual internal validation RMSE',
        config_selection_note='Generic selection text in history v1 config refers to neural/ES selection; boosting uses its inherited pooled RMSE callback. Each block excludes its own evaluation targets from either selection; preceding blocks can become later fitting data.'))
    print(compared.to_string(index=False), flush=True)


if __name__ == '__main__':
    main()
