"""Paired state-weather ablation with the terminal pathway held fixed."""
import json

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from inseason_13year_data import ROOT, RECIPES, BLOCKS, load, partition
from inseason_nested_common import LABELS, verify
from review_revision_data import sha256
from run_inseason_no_weather_eval import eval_root, RATIOS
from run_inseason_no_weather_state import verify_state
from run_review_revision_parallel import atomic_json
from summarize_inseason_13year import annual_gain
from summarize_inseason_six_direct import complete_score
from summarize_inseason_state_controls import collect as collect_controls, aggregate_states

OUT = ROOT / 'visualize/paper_experiments/inseason_no_weather_v1'
TEX = ROOT / 'Paper/iclr2027/sections'
CN = dict(maize='玉米',rice='水稻',soybean='大豆',wheat='小麦')


def collect():
    core,core_annual,_,_,core_state,sources,_ = collect_controls()
    rows,annual,paired,states,registry = [],[],[],[],[]
    for crop in RECIPES:
        raw,_ = load(crop)
        labels = {key:np.concatenate([raw[key][partition(raw,cutoff)['evaluation']]
            for cutoff in BLOCKS]) for key in LABELS}
        outputs = {round(100*r):[] for r in RATIOS}
        references = {key:[] for key in outputs}
        for cutoff in BLOCKS:
            root = eval_root(crop,cutoff)
            if verify(root)['smoke']:
                raise ValueError('Smoke cannot enter weather-ablation summary')
            sources[str(root / 'complete.json')] = sha256(root / 'complete.json')
            provenance = json.loads((root / 'provenance.json').read_text())
            for path,digest in provenance['sources'].items():
                if sha256(ROOT / path) != digest:
                    raise ValueError('Changed weather-ablation upstream source')
                sources[path] = digest
            for product in RECIPES[crop].split('_'):
                state,_ = verify_state(crop,product,cutoff)
                registry.append(dict(crop=crop,product=product,cutoff=cutoff,seed=42,
                    weight=str(state / 'model.pt'),sha256=sha256(state / 'model.pt'),
                    config=str(state / 'config.json'),manifest=str(state / 'complete.json')))
            states.append(pd.read_csv(root / 'state_annual.csv'))
            ix = partition(raw,cutoff)['evaluation']
            from run_inseason_state_controls import root_for
            for percent in outputs:
                with np.load(root / f'tail_{percent:02d}.npz') as saved:
                    for key in LABELS:
                        np.testing.assert_array_equal(saved[key],raw[key][ix])
                    outputs[percent].append(saved['prediction'].copy())
                with np.load(root_for(crop,cutoff) / f'tail_{percent:02d}_biid.npz') as saved:
                    for key in LABELS:
                        np.testing.assert_array_equal(saved[key],raw[key][ix])
                    references[percent].append(saved['prediction'].copy())
        for percent,pieces in outputs.items():
            prediction = np.concatenate(pieces)
            metrics = complete_score(labels,prediction)
            rows.append(dict(crop=crop,percent=percent,method='no_weather',
                mean_annual_rmse=metrics['mean_annual_rmse'],pooled_rmse=metrics['pooled_rmse']))
            annual.extend(dict(crop=crop,percent=percent,method='no_weather',year=int(year),rmse=value)
                for year,value in metrics['per_year_rmse'].items())
            paired.append(dict(crop=crop,percent=percent,reference='no_weather',
                **annual_gain(labels['target'],np.concatenate(references[percent]),prediction,labels['year'])))
    if len(registry) != 15:
        raise ValueError('Expected fifteen state-weather refits')
    state_annual = pd.concat(states,ignore_index=True)
    aggregate = aggregate_states(state_annual)
    if len(aggregate) != 15:
        raise ValueError('Incomplete weather-ablation state conditions')
    return (pd.concat([core[core.method.isin(['biid','climatology'])],pd.DataFrame(rows)],ignore_index=True),
        pd.concat([core_annual[core_annual.method.isin(['biid','climatology'])],pd.DataFrame(annual)],ignore_index=True),
        pd.DataFrame(paired),state_annual,
        pd.concat([core_state[core_state.method.eq('biid')],aggregate],ignore_index=True),sources,registry)


def export(frame,paired,states):
    def table(filename,caption,label,columns,header,lines):
        (TEX / filename).write_text('% Generated by scripts/summarize_inseason_no_weather.py\n'
            '\\begin{table}[htbp]\n\\centering\\small\n'+f'\\caption{{{caption}}}\n'
            +f'\\label{{{label}}}\n\\begin{{tabular}}{{{columns}}}\n\\toprule\n'
            +header+r' \\'+'\n\\midrule\n'+'\n'.join(lines)+'\n\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    lines = []
    for percent in (10,30,50):
        sub = frame[frame.percent.eq(percent)].pivot(index='method',columns='crop',values='mean_annual_rmse')
        for method,name in [('biid','Weather-driven BIID'),('no_weather','BIID refit without state weather')]:
            lines.append(' & '.join([f'{percent}\\%',name]+[f'{sub.loc[method,c]:.4f}' for c in RECIPES])+r' \\')
    table('inseason_weather_yield_table.tex',
        'Removing weather only from the state-transition pathway, with matched-capacity retraining. '
        'The terminal head retains the same meteorological inputs and frozen weights. '
        'Entries are thirteen-year mean annual yield RMSE (t/ha).',
        'tab:inseason_weather_yield','llrrrr','Suffix & State model & Maize & Rice & Soybean & Wheat',lines)
    lines = []
    for (crop,product,percent),group in states.groupby(['crop','product','percent']):
        sub = group.set_index('method')
        cells = [crop.title(),product.upper(),f'{percent}\\%']
        cells += [f'{sub.loc[m,"mean_annual_rmse"]:.4f}' for m in ('biid','no_weather')]
        cells += [f'{sub.loc[m,"mean_annual_anomaly_correlation"]:.3f}' for m in ('biid','no_weather')]
        lines.append(' & '.join(cells)+r' \\')
    table('inseason_weather_state_table.tex',
        'Hidden-slot state accuracy with and without state-transition weather. '
        'RMSE uses NDVI units or GPP gC m$^{-2}$ day$^{-1}$; correlations remove training-period grid--month climatology. '
        'Both statistics are averaged across the same thirteen years.',
        'tab:inseason_weather_state','lllrrrr',
        'Crop & State & Suffix & Weather RMSE & No weather & Weather corr. & No weather',lines)
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'pdf.fonttype':42})
    fig,axes = plt.subplots(2,2,figsize=(10,7.2))
    fig.subplots_adjust(left=.10,right=.97,bottom=.16,top=.95,hspace=.42,wspace=.28)
    names = dict(biid='Weather-driven BIID',no_weather='No state weather (retrained)',climatology='Climatology completion')
    colors = dict(biid='#1c7c68',no_weather='#3267a3',climatology='#ba6338')
    for crop,ax in zip(RECIPES,axes.flat):
        for method in names:
            sub = frame[frame.crop.eq(crop) & frame.method.eq(method)].sort_values('percent')
            ax.plot(sub.percent,sub.mean_annual_rmse,'o-',color=colors[method],label=names[method],markersize=4)
        ax.set_title(crop.title()+' | '+RECIPES[crop].upper().replace('_',' + '),fontsize=11)
        ax.set_xticks([10,30,50])
        ax.set_xlabel('Nominal unobserved suffix (%)')
        ax.set_ylabel('Mean annual yield RMSE (t/ha)')
        ax.grid(axis='y',alpha=.2)
        ax.spines[['top','right']].set_visible(False)
    fig.legend(*axes.flat[0].get_legend_handles_labels(),loc='lower center',ncol=3,frameon=False,fontsize=9)
    for ext in ('png','pdf'):
        fig.savefig(OUT / f'state_weather_ablation.{ext}',dpi=220,bbox_inches='tight')
    plt.close(fig)
    report = ['# 状态气象驱动消融：十三年结果','',
        '这不是删掉整个系统的气象。只把状态转移的气象设为恒定零，并重新训练15个相同结构的BIID；产量端仍读取原气象、同样前缀和冻结历史/产量头。', '',
        '| 作物 | 后缀 | 原模型产量RMSE | 无状态气象的产量RMSE | 气象驱动降幅 | 更好年份 |',
        '|---|---:|---:|---:|---:|---:|']
    for crop in RECIPES:
        for percent in (10,30,50):
            sub = frame[frame.crop.eq(crop) & frame.percent.eq(percent)].set_index('method')
            row = paired[paired.crop.eq(crop) & paired.percent.eq(percent)].iloc[0]
            report.append(f'| {CN[crop]} | {percent}% | {sub.loc["biid","mean_annual_rmse"]:.4f} | '
                f'{sub.loc["no_weather","mean_annual_rmse"]:.4f} | {row.annual_mean_rmse_gain:+.2f}% | {int(row.positive_years)}/13 |')
    report += ['',f'![状态气象路径消融]({OUT}/state_weather_ablation.png)','',
        '怎么看：每个面板是一种作物，横轴越右表示更多活动槽未观测，纵轴越低产量误差越小。绿色与蓝色的差别只来自是否使用气象训练和驱动状态；橙色是原来的常态补全。', '',
        '状态和产量分开计分：状态误差降低不必然传成产量误差降低。此实验不验证真实天气预报、不删除产量端天气、不测未见地区泛化，也不代表多种子确认。', '',
        f'- 完整产量和状态统计：`{OUT}/yield_scores.csv`、`{OUT}/state_scores.csv`。',
        f'- 每年结果：`{OUT}/yield_annual.csv`、`{OUT}/state_annual.csv`。',
        f'- 15个新权重：`{OUT}/checkpoint_registry.csv`。',
        f'- 样本、上游和源文件核验：`{OUT}/audit.json`。']
    (OUT / '结果说明.md').write_text('\n'.join(report)+'\n')


def main():
    OUT.mkdir(parents=True,exist_ok=True)
    frame,annual,paired,state_annual,states,sources,registry = collect()
    for name,data in [('yield_scores',frame),('yield_annual',annual),('paired_gains',paired),
        ('state_annual',state_annual),('state_scores',states)]:
        data.to_csv(OUT / (name+'.csv'),index=False)
    pd.DataFrame(registry).to_csv(OUT / 'checkpoint_registry.csv',index=False)
    export(frame,paired,states)
    atomic_json(OUT / 'audit.json',dict(sources=sources,new_state_fits=15,new_yield_fits=0,
        yield_conditions=36,all_thirteen_years=True,terminal_weather_unchanged=True,seed=42,
        generator_sha256=sha256(ROOT / 'scripts/summarize_inseason_no_weather.py')))
    print(paired.to_string(index=False),flush=True)


if __name__ == '__main__':
    main()
