"""Verified terminal-path and same-information temporal-coordinate evidence."""
import argparse
import json
from pathlib import Path

import joblib
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch

from inseason_13year_data import ROOT, CACHE, RECIPES, BLOCKS, load, partition
from inseason_nested_common import LABELS, verify
from inseason_terminal_paths import CONDITIONS, RATIOS, MODES, check_splits
from run_inseason_terminal_paths import root_for as terminal_root
from run_inseason_calendar_coordinates import root_for as calendar_root, reference_root, MODELS
from run_ndvi_signal_permutation import check_files
from run_review_revision_parallel import atomic_json
from summarize_inseason_13year import annual_gain
from summarize_inseason_six_direct import complete_score
from review_revision_data import sha256

BASE = ROOT / 'visualize/paper_experiments'
TEX = ROOT / 'Paper/iclr2027/sections'
NAMES = dict(full='Full terminal input', no_weather='No terminal weather',
    no_quality='No terminal product support', no_weather_quality='Neither terminal path')
COORDINATES = dict(packed='Packed active slots', calendar='Natural-month coordinates')
MODEL_NAMES = dict(cnn_rnn='CNN--RNN (adapted)', transformer='Transformer')


def table(name, caption, label, columns, header, rows):
    (TEX / name).write_text('% Generated by scripts/summarize_inseason_mechanism_completeness.py\n'
        '\\begin{table}[htbp]\n\\centering\\small\n'+f'\\caption{{{caption}}}\n\\label{{{label}}}\n'
        +f'\\begin{{tabular}}{{{columns}}}\n\\toprule\n'+header+r' \\'+'\n\\midrule\n'
        +'\n'.join(rows)+'\n\\bottomrule\n\\end{tabular}\n\\end{table}\n')


def labels_for(raw):
    return {k: np.concatenate([raw[k][partition(raw, c)['evaluation']] for c in BLOCKS]) for k in LABELS}


def load_predictions(path, raw, indices):
    with np.load(path) as saved:
        for key in LABELS:
            np.testing.assert_array_equal(saved[key], raw[key][indices])
        return saved['prediction'].copy()


def measured(labels, prediction, identity):
    metric = complete_score(labels, prediction)
    row = dict(**identity, mean_annual_rmse=metric['mean_annual_rmse'], pooled_rmse=metric['pooled_rmse'])
    annual = [dict(**identity, year=int(year), rmse=value) for year, value in metric['per_year_rmse'].items()]
    return row, annual


def collect_terminal():
    rows, annual, pairs, completion, registry, sources = [], [], [], [], [], {}
    for crop in RECIPES:
        raw, _ = load(crop)
        labels = labels_for(raw)
        predictions = {(condition, round(100*r), mode): [] for condition in CONDITIONS for r in RATIOS for mode in MODES}
        for cutoff in BLOCKS:
            root = terminal_root(crop, cutoff)
            marker = verify(root)
            if marker['smoke'] or not marker['full_rebuild_verified']:
                raise ValueError('Missing original terminal reconstruction')
            sources[str(root / 'complete.json')] = sha256(root / 'complete.json')
            cfg = json.loads((root / 'config.json').read_text())
            if (cfg['crop'], cfg['cutoff'], cfg['seed'], cfg['recipe']) != (crop, cutoff, 42, RECIPES[crop]):
                raise ValueError('Wrong terminal configuration identity')
            for path, digest in cfg['sources'].items():
                if sha256(Path(path)) != digest:
                    raise ValueError('Changed original terminal source')
                sources[path] = digest
            index = partition(raw, cutoff)['evaluation']
            for condition in CONDITIONS:
                dest = root / condition
                verify(dest)
                records = json.loads((dest / 'metrics.json').read_text())['fits']
                for branch in records:
                    weight = dest / branch['branch'] / 'model.joblib'
                    model = joblib.load(weight)
                    removed = check_splits(model, condition)
                    if removed != branch['removed_columns'] or model.get_params() != branch['parameters']:
                        raise ValueError('Changed terminal mask or tree parameters')
                    if condition == 'full' and branch['original_prediction_max_error'] > 1e-12:
                        raise ValueError('Original terminal prediction was not reconstructed')
                    registry.append(dict(crop=crop, cutoff=cutoff, condition=condition, branch=branch['branch'],
                        weight=str(weight), sha256=sha256(weight), config=str(root / 'config.json'),
                        removed_columns=json.dumps(removed), full_rebuild_error=branch['original_prediction_max_error']))
                for ratio in RATIOS:
                    percent = round(100*ratio)
                    for mode in MODES:
                        path = dest / f'tail_{percent:02d}_{mode}.npz'
                        prediction = load_predictions(path, raw, index)
                        if condition == 'full':
                            expected = np.load(CACHE / crop / f'world_{cutoff}_{RECIPES[crop]}_{mode}_{percent:03d}.npy')
                            np.testing.assert_allclose(prediction, expected, rtol=0, atol=1e-12)
                        predictions[condition, percent, mode].append(prediction)
                        sources[str(path)] = sha256(path)
        predictions = {key: np.concatenate(value) for key, value in predictions.items()}
        for (condition, percent, mode), prediction in predictions.items():
            row, years = measured(labels, prediction, dict(crop=crop, condition=condition, percent=percent, mode=mode))
            rows.append(row)
            annual.extend(years)
            if condition != 'full':
                pairs.append(dict(crop=crop, removed=condition, percent=percent, mode=mode,
                    **annual_gain(labels['target'], predictions['full', percent, mode], prediction, labels['year'])))
            if mode == 'biid':
                completion.append(dict(crop=crop, condition=condition, percent=percent,
                    **annual_gain(labels['target'], prediction, predictions[condition, percent, 'climatology'], labels['year'])))
    if len(registry) != 60 or len(rows) != 96 or len(completion) != 48:
        raise ValueError('Incomplete terminal-path matrix')
    return pd.DataFrame(rows), pd.DataFrame(annual), pd.DataFrame(pairs), pd.DataFrame(completion), registry, sources


def collect_calendar():
    rows, annual, pairs, registry, sources = [], [], [], [], {}
    for crop in RECIPES:
        raw, _ = load(crop)
        labels = labels_for(raw)
        for model in MODELS:
            predictions = {coordinate: [] for coordinate in COORDINATES}
            for cutoff in BLOCKS:
                root = calendar_root(crop, cutoff, model)
                marker = verify(root)
                if marker['smoke'] or not marker['original_prediction_replayed'] or not marker['normalization_matched']:
                    raise ValueError('Missing coordinate identity/replay evidence')
                original = reference_root(crop, cutoff, model)
                cfg = json.loads((root / 'config.json').read_text())
                if cfg['reference_marker_sha256'] != sha256(original / 'complete.json'):
                    raise ValueError('Changed original packed reference')
                old_marker = json.loads((original / 'complete.json').read_text())
                check_files(original, old_marker['files'])
                for name, digest in old_marker['code_sha256'].items():
                    if sha256(ROOT / 'scripts' / name) != digest:
                        raise ValueError('Changed original coordinate training source')
                if old_marker['smoke'] or (cfg['crop'], cfg['cutoff'], cfg['model'], cfg['ratio']) != (crop, cutoff, model, .1):
                    raise ValueError('Incorrect coordinate configuration identity')
                sources[str(root / 'complete.json')] = sha256(root / 'complete.json')
                sources[str(original / 'complete.json')] = sha256(original / 'complete.json')
                old = original / 'tail_10'
                for filename in ('inner_normalization.json', 'metrics.json'):
                    new_norm = json.loads((root / filename).read_text())
                    old_norm = json.loads((old / filename).read_text())
                    if filename == 'metrics.json':
                        new_norm, old_norm = new_norm['full_normalization'], old_norm['full_normalization']
                    if new_norm != old_norm:
                        raise ValueError('Changed normalization between temporal coordinates')
                old_state = torch.load(old / 'model.pt', map_location='cpu', weights_only=True)
                new_state = torch.load(root / 'model.pt', map_location='cpu', weights_only=True)
                if {k: tuple(v.shape) for k, v in old_state.items()} != {k: tuple(v.shape) for k, v in new_state.items()}:
                    raise ValueError('Temporal comparison changed model capacity')
                params = sum(v.numel() for v in new_state.values())
                index = partition(raw, cutoff)['evaluation']
                for coordinate, dest in [('packed', old), ('calendar', root)]:
                    path = dest / 'evaluation_predictions.npz'
                    predictions[coordinate].append(load_predictions(path, raw, index))
                    sources[str(path)] = sha256(path)
                    registry.append(dict(crop=crop, cutoff=cutoff, model=model, coordinate=coordinate,
                        weight=str(dest / 'model.pt'), sha256=sha256(dest / 'model.pt'),
                        config=str((original if coordinate == 'packed' else root) / 'config.json'),
                        parameter_elements=params, normalization_matched=True))
            predictions = {key: np.concatenate(value) for key, value in predictions.items()}
            for coordinate, prediction in predictions.items():
                row, years = measured(labels, prediction, dict(crop=crop, model=model, coordinate=coordinate))
                rows.append(row)
                annual.extend(years)
            pairs.append(dict(crop=crop, model=model,
                **annual_gain(labels['target'], predictions['packed'], predictions['calendar'], labels['year'])))
    if len(registry) != 48 or len(rows) != 16:
        raise ValueError('Incomplete coordinate matrix')
    return pd.DataFrame(rows), pd.DataFrame(annual), pd.DataFrame(pairs), registry, sources


def plot_terminal(frame, out):
    fig, axes = plt.subplots(2, 2, figsize=(10, 7.2))
    fig.subplots_adjust(left=.10, right=.97, bottom=.18, top=.95, hspace=.43, wspace=.28)
    for crop, ax in zip(RECIPES, axes.flat):
        for condition, color in zip(CONDITIONS, ('#1c7c68', '#3267a3', '#b7673d', '#777777')):
            sub = frame[frame.crop.eq(crop) & frame.condition.eq(condition) & frame['mode'].eq('biid')].sort_values('percent')
            ax.plot(sub.percent, sub.mean_annual_rmse, 'o-', color=color, label=NAMES[condition], markersize=4)
        ax.set_title(crop.title()+' | '+RECIPES[crop].upper().replace('_', ' + '), fontsize=11)
        ax.set_xticks([10, 30, 50])
        ax.set_xlabel('Nominal unobserved suffix (%)')
        ax.set_ylabel('Mean annual yield RMSE (t/ha)')
        ax.spines[['top', 'right']].set_visible(False)
        ax.grid(axis='y', alpha=.2)
    fig.legend(*axes.flat[0].get_legend_handles_labels(), loc='lower center', ncol=2, frameon=False)
    for ext in ('png', 'pdf'):
        fig.savefig(out / f'terminal_path_comparison.{ext}', dpi=220, bbox_inches='tight')
    plt.close(fig)


def export_terminal(frame, paired, completion, out):
    rows, gains = [], []
    for percent in (10, 30, 50):
        sub = frame[frame.percent.eq(percent) & frame['mode'].eq('biid')].pivot(index='condition', columns='crop', values='mean_annual_rmse')
        comp = completion[completion.percent.eq(percent)].pivot(index='condition', columns='crop', values='annual_mean_rmse_gain')
        for condition in CONDITIONS:
            first = [f'{percent}\\%', NAMES[condition]]
            rows.append(' & '.join(first+[f'{sub.loc[condition,c]:.4f}' for c in RECIPES])+r' \\')
            gains.append(' & '.join(first+[f'{comp.loc[condition,c]:+.3f}' for c in RECIPES])+r' \\')
    table('inseason_terminal_paths_table.tex',
        'Terminal-path ablations with the original weather-driven BIID trajectories and historical anchors. '
        'Entries are thirteen-year mean annual yield RMSE (t/ha). Only terminal inputs are removed and refitted '
        'at the original selected tree counts; full-input refits reconstruct the saved predictions.',
        'tab:inseason_terminal_paths', 'llrrrr', 'Suffix & Terminal input & Maize & Rice & Soybean & Wheat', rows)
    table('inseason_terminal_completion_table.tex',
        'BIID versus climatology under each fixed terminal head. Entries are reductions in thirteen-year '
        'mean annual yield RMSE (\\%). Positive values favor BIID completion. Within each row only the predicted '
        'suffix changes; observations, metadata and terminal weights remain fixed.',
        'tab:inseason_terminal_completion', 'llrrrr', 'Suffix & Terminal input & Maize & Rice & Soybean & Wheat', gains)
    plot_terminal(frame, out)
    text = ['# 世界模型终端路径消融：十三年结果', '',
        '原历史专家和BIID预测不变，只删除产量头的天气直连/共享产品支持，并按原已选树数重训。60个分支拟合中15个完整输入重建原模型，45个删除对照；不是60个新框架，也没有重新挑种子。', '',
        f'![终端输入路径]({out}/terminal_path_comparison.png)', '',
        '怎么看：一个面板是一种作物，横轴越右表示需要预测的后缀越长；纵轴越低越好。绿线保留全部终端输入，蓝线删除终端天气，橙线删除终端支持，灰线同时删除两者。各线的BIID预测完全相同，所以这不是状态预测误差的变化。', '',
        '| 主截点条件 | 玉米RMSE | 水稻RMSE | 大豆RMSE | 小麦RMSE |', '|---|---:|---:|---:|---:|']
    values = frame[frame.percent.eq(10) & frame['mode'].eq('biid')].pivot(index='condition', columns='crop', values='mean_annual_rmse')
    for c in CONDITIONS:
        text.append('| '+NAMES[c]+' | '+' | '.join(f'{values.loc[c,crop]:.4f}' for crop in RECIPES)+' |')
    text += ['', '## 保留终端输入的作用', '', '下列正数表示完整头更好，负数表示删除后的头更好；均为年均RMSE之比的改善。', '',
        '| 作物 | 删除项 | 完整头相对改善 | 更好年份 |', '|---|---|---:|---:|']
    for _, row in paired[paired.percent.eq(10) & paired['mode'].eq('biid')].iterrows():
        text.append(f'| {row.crop} | {NAMES[row.removed]} | {row.annual_mean_rmse_gain:+.2f}% | {int(row.positive_years)}/13 |')
    text += ['', '## 同一头内BIID相对常态补全', '',
        '| 作物 | 未观测后缀 | 完整输入 | 无终端天气 | 无终端支持 | 两者均无 |', '|---|---:|---:|---:|---:|---:|']
    for crop in RECIPES:
        for percent in (10, 30, 50):
            sub = completion[completion.crop.eq(crop) & completion.percent.eq(percent)].set_index('condition')
            text.append(f'| {crop} | {percent}% | '+' | '.join(f'{sub.loc[c,"annual_mean_rmse_gain"]:+.3f}%' for c in CONDITIONS)+' |')
    text += ['', '这张表只替换后缀，正数才表示该头使用BIID比使用常态更好。不能把绿线相对历史的全部收益都算到状态演化上。', '',
        '预算固定在原开发选择的树数，各删除条件没有重新选轮次；质量删除只针对终端六个字段，不取消轨迹本身的缺失信息或状态初始化质量。该实验保留原开发来源，不是独立确认，也不是全流程多种子。', '',
        f'- 全部96项13年汇总及逐年结果：`{out}/scores.csv`、`annual.csv`。',
        f'- 输入路径和同头补全的配对统计：`{out}/paired_gains.csv`、`completion_gains.csv`。',
        f'- 60个权重及来源核验：`{out}/checkpoint_registry.csv`、`audit.json`。']
    (out / '结果说明.md').write_text('\n'.join(text)+'\n')


def export_calendar(frame, paired, out):
    rows = []
    for model in MODELS:
        sub = frame[frame.model.eq(model)].pivot(index='coordinate', columns='crop', values='mean_annual_rmse')
        for coordinate in COORDINATES:
            rows.append(' & '.join([MODEL_NAMES[model], COORDINATES[coordinate]]+
                [f'{sub.loc[coordinate,c]:.4f}' for c in RECIPES])+r' \\')
    table('inseason_calendar_coordinates_table.tex',
        'Temporal coordinates with identical seasonal information at the 10\\% suffix. '
        'The same masked active tokens are either packed or placed at their source natural months; '
        'calendar features, static summaries, samples and normalization remain unchanged. '
        'Entries are thirteen-year mean annual yield RMSE (t/ha).',
        'tab:inseason_calendar_coordinates', 'llrrrr', 'Model & Coordinates & Maize & Rice & Soybean & Wheat', rows)
    fig, ax = plt.subplots(figsize=(9.5, 4.6))
    fig.subplots_adjust(left=.10, right=.98, bottom=.22, top=.92)
    centers = np.arange(4)
    for offset, (model, color) in enumerate(zip(MODELS, ('#3267a3', '#b7673d'))):
        sub = paired[paired.model.eq(model)].set_index('crop')
        ax.bar(centers+(offset-.5)*.30, [sub.loc[c,'annual_mean_rmse_gain'] for c in RECIPES],
            width=.29, label=MODEL_NAMES[model].replace('--','-'), color=color)
    ax.set_xticks(centers, [c.title() for c in RECIPES])
    ax.axhline(0, color='.25', linewidth=.8)
    ax.set_ylabel('Packed-coordinate RMSE reduction (%)')
    ax.set_title('Same observed months and inputs | nominal 10% suffix', fontsize=11)
    ax.grid(axis='y', alpha=.18)
    ax.set_axisbelow(True)
    ax.spines[['top','right']].set_visible(False)
    fig.legend(*ax.get_legend_handles_labels(), loc='lower center', ncol=2, frameon=False)
    for ext in ('png','pdf'):
        fig.savefig(out / f'calendar_coordinate_comparison.{ext}', dpi=220, bbox_inches='tight')
    plt.close(fig)
    text = ['# 活动槽与自然月坐标：十三年结果', '',
        '同样历史、气象和可见遥感，不增加非活动月输入。原活动槽模型24个复用，新自然月模型24个重新选择内部轮次后完整拟合。', '',
        '| 模型 | 坐标 | 玉米 | 水稻 | 大豆 | 小麦 |', '|---|---|---:|---:|---:|---:|']
    for model in MODELS:
        sub = frame[frame.model.eq(model)].pivot(index='coordinate', columns='crop', values='mean_annual_rmse')
        for coordinate in COORDINATES:
            text.append('| '+MODEL_NAMES[model]+' | '+COORDINATES[coordinate]+' | '+
                ' | '.join(f'{sub.loc[coordinate,c]:.4f}' for c in RECIPES)+' |')
    text += ['', f'![同信息坐标对照]({out}/calendar_coordinate_comparison.png)', '',
        '怎么看：正柱表示活动槽排列的误差低于自然月排列，负柱表示自然月排列更好。两种颜色对应不同模型。它不是有无遥感，也不是全系统增益。', '',
        '| 作物 | 模型 | 活动槽相对自然月改善 | 更好年份 |', '|---|---|---:|---:|']
    for _, row in paired.iterrows():
        text.append(f'| {row.crop} | {MODEL_NAMES[row.model]} | {row.annual_mean_rmse_gain:+.2f}% | {int(row.positive_years)}/13 |')
    text += ['', '原版已经携带自然月日历字段，因此测试的是同信息条件下的位置编码和邻接关系，不是日历信息有无。不同模型的差异不应泛化为普遍物候优势；也不证明跨年作季修复或世界模型递推结构的优越性。', '',
        f'- 分数、逐年与配对结果：`{out}/scores.csv`、`annual.csv`、`paired_gains.csv`。',
        f'- 48个含复用权重索引、参数量与来源核验：`{out}/checkpoint_registry.csv`、`audit.json`。']
    (out / '结果说明.md').write_text('\n'.join(text)+'\n')


def main(study):
    plt.rcParams.update({'font.family':'DejaVu Sans', 'font.size':10, 'pdf.fonttype':42})
    out = BASE / ('inseason_terminal_paths_v1' if study == 'terminal' else 'inseason_calendar_coordinates_v1')
    out.mkdir(parents=True, exist_ok=True)
    if study == 'terminal':
        frame, annual, paired, completion, registry, sources = collect_terminal()
        completion.to_csv(out / 'completion_gains.csv', index=False)
        export_terminal(frame, paired, completion, out)
    else:
        frame, annual, paired, registry, sources = collect_calendar()
        export_calendar(frame, paired, out)
    for name, data in [('scores',frame),('annual',annual),('paired_gains',paired),('checkpoint_registry',pd.DataFrame(registry))]:
        data.to_csv(out / (name+'.csv'), index=False)
    atomic_json(out / 'audit.json', dict(study=study, sources=sources, seed=42,
        all_thirteen_years=True, all_registered_conditions=True, weight_records=len(registry),
        new_branch_fits=60 if study == 'terminal' else 24,
        original_rebuilds=15 if study == 'terminal' else 0,
        original_models_reused=0 if study == 'terminal' else 24,
        generator_sha256=sha256(Path(__file__))))
    print(frame.to_string(index=False), flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--study', choices=('terminal','calendar'), required=True)
    main(parser.parse_args().study)
