"""All five direct signal conditions on one fixed population and issue point."""
import json

import joblib
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from inseason_13year_data import ROOT, CACHE, RECIPES, BLOCKS, load, partition
from inseason_nested_common import LABELS
from inseason_signal_values import CONDITIONS, mask_values
from inseason_complete_inputs import flat_features
from run_inseason_signal_values import root_for, verify
from review_revision_data import sha256
from run_review_revision_parallel import atomic_json
from summarize_inseason_six_direct import complete_score
from summarize_inseason_13year import annual_gain

OUT = ROOT / 'visualize/paper_experiments/inseason_signal_values_v1'
TEX = ROOT / 'Paper/iclr2027/sections'
NAMES = dict(metadata='Shared background', lai='LAI', ndvi='NDVI', gpp='GPP', ndvi_gpp='NDVI + GPP')


def collect():
    scores, annual, gains, registry, sources = [], [], [], [], {}
    for crop in RECIPES:
        raw, _ = load(crop)
        sources[str(CACHE / crop / 'manifest.json')] = sha256(CACHE / crop / 'manifest.json')
        labels = {key: np.concatenate([raw[key][partition(raw, end)['evaluation']]
            for end in BLOCKS]) for key in LABELS}
        predictions = {s: [] for s in CONDITIONS}
        for end in BLOCKS:
            ix = partition(raw, end)['evaluation']
            normalization = None
            for condition in CONDITIONS:
                root = root_for(crop, end, condition)
                marker = verify(root)
                config = json.loads((root / 'config.json').read_text())
                if marker['smoke'] or config['condition'] != condition or config['crop'] != crop or config['cutoff'] != end:
                    raise ValueError('Invalid signal-value condition')
                if config['seed'] != 42 or config['ratio'] != .1:
                    raise ValueError('Changed signal-value evaluation protocol')
                sources[str(root / 'complete.json')] = sha256(root / 'complete.json')
                metrics = json.loads((root / 'metrics.json').read_text())
                current = metrics['full_normalization']
                if normalization is not None and normalization != current:
                    raise ValueError('Signal conditions changed shared fitting normalization')
                normalization = current
                path = root / 'evaluation_predictions.npz'
                with np.load(path) as saved:
                    for key in LABELS:
                        np.testing.assert_array_equal(saved[key], raw[key][ix])
                    predictions[condition].append(saved['prediction'].copy())
                sources[str(path)] = sha256(path)
                products = 2 if condition == 'ndvi_gpp' else 1
                probe = dict(sequence=np.ones((1, 12, 38+7*products)), static=np.ones((1, 21+24*products)))
                removed = np.flatnonzero(flat_features(mask_values(probe, condition))[0] == 0)
                model = joblib.load(root / 'model.joblib')
                if np.any(model.booster_.feature_importance('split')[removed] != 0):
                    raise ValueError('Signal tree uses a removed column')
                registry.append(dict(crop=crop, cutoff=end, condition=condition, seed=42,
                    weight=str(root / 'model.joblib'), sha256=sha256(root / 'model.joblib'),
                    config=str(root / 'config.json'), metrics=str(root / 'metrics.json'),
                    removed_columns=json.dumps(removed.tolist()), removed_tree_splits_verified=True))
        predictions = {key: np.concatenate(parts) for key, parts in predictions.items()}
        for condition, prediction in predictions.items():
            metric = complete_score(labels, prediction)
            scores.append(dict(crop=crop, condition=condition, mean_annual_rmse=metric['mean_annual_rmse'],
                pooled_rmse=metric['pooled_rmse']))
            annual.extend(dict(crop=crop, condition=condition, year=int(y), rmse=value)
                for y, value in metric['per_year_rmse'].items())
            if condition != 'metadata':
                gains.append(dict(crop=crop, condition=condition,
                    **annual_gain(labels['target'], prediction, predictions['metadata'], labels['year'])))
    if len(registry) != 60:
        raise ValueError('Expected sixty matched signal-value models')
    return pd.DataFrame(scores), pd.DataFrame(annual), pd.DataFrame(gains), registry, sources


def export(scores, gains):
    values = scores.pivot(index='condition', columns='crop', values='mean_annual_rmse')
    rows = [' & '.join([NAMES[s]]+[f'{values.loc[s,c]:.4f}' for c in RECIPES])+r' \\' for s in CONDITIONS]
    (TEX / 'inseason_signal_values_table.tex').write_text(
        '% Generated by scripts/summarize_inseason_signal_values.py\n'
        '\\begin{table}[htbp]\n\\centering\\small\n'
        '\\caption{Input-matched vegetation signals in direct LightGBM at the 10\\% suffix. '
        'Entries are thirteen-year mean annual yield RMSE (t/ha). All rows retain history, '
        'weather, calendar and the same issue-masked product-support fields. '
        'Product-specific previous quality is disabled in every condition.}\n'
        '\\label{tab:inseason_signal_values}\n\\begin{tabular}{lrrrr}\n\\toprule\n'
        'Added signal & Maize & Rice & Soybean & Wheat \\\\\n\\midrule\n'+
        '\n'.join(rows)+'\n\\bottomrule\n\\end{tabular}\n\\end{table}\n')
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'pdf.fonttype':42})
    fig, ax = plt.subplots(figsize=(9.2, 4.6))
    fig.subplots_adjust(left=.11, right=.98, top=.92, bottom=.2)
    for i, (condition, color) in enumerate(zip(CONDITIONS[1:], ('#b7673d','#3267a3','#1c7c68','#985d91'))):
        frame = gains[gains.condition.eq(condition)].set_index('crop')
        ax.bar(np.arange(4)+(i-1.5)*.2, [frame.loc[c,'annual_mean_rmse_gain'] for c in RECIPES],
            width=.19, label=NAMES[condition], color=color)
    ax.axhline(0, color='.25', linewidth=.8)
    ax.set_xticks(np.arange(4), [c.title() for c in RECIPES])
    ax.set_ylabel('RMSE reduction vs shared background (%)')
    ax.set_title('Direct LightGBM | nominal 10% unobserved suffix', fontsize=11)
    ax.spines[['top','right']].set_visible(False)
    ax.grid(axis='y', alpha=.2)
    ax.set_axisbelow(True)
    fig.legend(*ax.get_legend_handles_labels(), loc='lower center', ncol=4, frameon=False)
    for ext in ('png','pdf'):
        fig.savefig(OUT / f'signal_value_comparison.{ext}', dpi=220, bbox_inches='tight')
    plt.close(fig)
    report = ['# LAI、NDVI、GPP同协议直接比较','',
        '同一种LightGBM、同样历史/气象/日历、相同13年样本和10%后缀；不训练状态模型，不改变原世界模型配方。', '',
        '| 所选信号 | 玉米 | 水稻 | 大豆 | 小麦 |','|---|---:|---:|---:|---:|']
    for condition in CONDITIONS:
        report.append('| '+NAMES[condition]+' | '+' | '.join(f'{values.loc[condition,c]:.4f}' for c in RECIPES)+' |')
    report += ['', '单位t/ha；13个年度空间RMSE等权平均，越低越好。', '',
        f'![信号价值比较]({OUT}/signal_value_comparison.png)', '',
        '怎么看：每种颜色是一种输入产品；正柱表示比同样背景、但不加入产品值的LightGBM更好。共享背景包括全部产品的相同可用性字段，因此不是纯历史参照。专属去年质量统一为零，不把LAI有限值伪装成原生质量。所有产品重新拟合，不拼接原主表分数。','',
        '| 作物 | 产品 | 相对背景的RMSE降幅 | 更好年份 |','|---|---|---:|---:|']
    for r in gains.itertuples():
        report.append(f'| {r.crop} | {NAMES[r.condition]} | {r.annual_mean_rmse_gain:+.2f}% | {r.positive_years}/13 |')
    report += ['', '产品差异反映可见值、上一年值和所选产品有效性的共同作用，不等于预测轨迹的排序，也没有验证LAI状态模型或严格收获年物候修复。', '',
        f'- 60个权重及实际删除列：`{OUT}/checkpoint_registry.csv`。',
        f'- 逐年数据、主分数、配对改善和来源：`{OUT}/annual.csv`、`scores.csv`、`paired_gains.csv`、`audit.json`。']
    (OUT / '结果说明.md').write_text('\n'.join(report)+'\n')


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    scores, annual, gains, registry, sources = collect()
    for name, frame in [('scores', scores), ('annual', annual), ('paired_gains', gains)]:
        frame.to_csv(OUT / (name+'.csv'), index=False)
    pd.DataFrame(registry).to_csv(OUT / 'checkpoint_registry.csv', index=False)
    export(scores, gains)
    atomic_json(OUT / 'audit.json', dict(sources=sources, new_models=60, all_thirteen_years=True,
        all_five_conditions=True, unchanged_shared_normalization=True, seed=42, ratio=.1,
        generator_sha256=sha256(ROOT / 'scripts/summarize_inseason_signal_values.py')))
    print(scores.to_string(index=False), flush=True)


if __name__ == '__main__':
    main()
